### ISSUE TITLE
The tasext container report http error

### ISSUE THREAD

**Issue by alekdu** [intel/telemetry-aware-scheduling#11]
2020/03/12 05:08:16 Get http://localhost:8111/cache/policies/default/demo-policy: dial tcp: i/o timeout

But actually I can use a service to expose 8111 to custer and use curl to access it.

Any possible reason for this ?

**Comment by alekdu** [comment]
Issue fixed by using http://127.0.0.1:8111 instead of http://localhost:8111. This could be tasext container issue, it cannot resolve localhost as hostname...

**Comment by killianmuldoon** [comment]
Huh, I'm not exactly sure what's going on there ?  Is the initial error from the TAS logs? If so we may need to change the dnsPolicy passed to it in the container. Alternatively this could be a proxy issue - especially given it's timing out, the issue doesn't seem to be no-resolve.

**Comment by alekdu** [comment]
The kube-scheduler can access https://localhost:9001 without problem, so the dnsPolicy should work.
The issue comes from tasext to access tascon http://localhost:8111, the cache server.
sounds like tascon has not localhost in hosts file.

**Comment by killianmuldoon** [comment]
Yeah - TAS components are build on scratch containers so the resolv.conf is created by the docker runtime. I'm getting output like 

```
nameserver 10.96.0.10
search default.svc.cluster.local svc.cluster.local cluster.local
options ndots:5
```

Which is from Docker/Kubernetes and might change with CRI implementation. I think changing the DNS policy passed in the deployment should take care of this. I'll take a look at the different options

**Comment by alekdu** [comment]
The easiest way is in my commit: - --cacheEndpoint=http://127.0.0.1:8111/cache/, this is to tell the tasext container to use 127.0.0.1 instead of default "localhost". There is no much interest to use DNS to resolve localhost since they are all inside the same POD.

**Comment by killianmuldoon** [comment]
Thanks for this - in #12 I added the bare IP (127.0.0.1:8111) as the default value for the cacheEndpoint. This should hopefully prevent people from running into the same issue.
